boogle/urls.py
from django.urls import path, include
from .views import index, like
from django.conf.urls import url

urlpatterns = [
    path('', index),
    path('like/', like),
]

jualdatapribadi/urls.py
from django.urls import path, include
from .views import index, signup, login_view
from django.conf.urls import url

app_name = 'jualdatapribadi'

urlpatterns = [
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    path('login/', login_view, name='login'),
]

status/urls.py
from django.urls import path, include
from .views import index, confirm, ran
from django.conf.urls import url
# from rest_framework.routers import DefaultRouter

# app_name = 'story7'

urlpatterns = [
    path('', index),
    path('confirm/', confirm),
    path('randcolor/<id>', ran)
]

tierlist/urls.py
from django.urls import path, include
from .views import index
from django.conf.urls import url

urlpatterns = [
    path('', index),
]

wewanttotalkaboutjoni/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('status.urls'), name='status'),
    path('tierlist/', include('tierlist.urls'), name='tierlist'),
    path('boogle/', include('boogle.urls'), name='boogle'),
    path('totallysafe/', include('jualdatapribadi.urls'), name='data'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boogle/models.py
from django.db import models

class Book(models.Model):
    id = models.CharField(max_length=200, primary_key=True ,unique=True)
    title = models.CharField(max_length=256)
    image_url = models.CharField(max_length=269)
    likes = models.IntegerField(default=0)

    class Meta:
        ordering = ('-likes',)

    def __str__(self):
        return self.title
    objects = models.Manager()

jualdatapribadi/models.py
from django.db import models
import datetime

from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateField(default=datetime.date.today)
    img_url = models.CharField(max_length=255)

    @property
    def full_name(self):
        return self.user.first_name + " " + self.user.last_name

    def __str__(self):
        return self.user.username
    objects = models.Manager()

status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    name = models.CharField(max_length=26)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    color = models.CharField(default="", max_length=7)

    def __str__(self):
        return self.name
    objects = models.Manager()
    
    class Meta:
        ordering = ('-created_at',)
        verbose_name_plural = 'Statuses'

tierlist/models.py
from django.db import models

# Create your models here.
class About(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        ordering = ('created_at',)
        verbose_name_plural = 'Abouts'

    def __str__(self):
        return self.title
    objects = models.Manager()

jualdatapribadi/forms.py
from django import forms
# from django.utils.timezone import now
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username','password']

status/forms.py
from django import forms
# from django.utils.timezone import now
from .models import Status

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name', 'content']

boogle/views.py
from django.shortcuts import get_object_or_404, render
from boogle.models import Book
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
import json

@csrf_exempt
def index(request):
    if request.method == "POST":
        books = list(Book.objects.values()[:5])
        return HttpResponse(json.dumps(books))
    else:
        return render(request, "boogle.html")

@csrf_exempt
def like(request):
    if request.method == 'POST':
        id = request.POST['id']
        title = request.POST['title']
        img = request.POST['img']
        book, created = Book.objects.get_or_create(id=id, title=title, image_url=img)
        book.likes += 1
        book.save()
        return HttpResponse(book.likes)

jualdatapribadi/views.py
from django.shortcuts import redirect, render, reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile
from .forms import UserForm

def index(request):
    username = request.session.get('username')
    try:
        userprof = UserProfile.objects.get(user__username=username)
    except:
        userprof = None
    context = {
        'userprof': userprof
    }
    return render(request, "home.html", context=context)
        
def signup(request):
    context = {
        'form': UserCreationForm
    }
    if request.method == 'POST':
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if password1 == password2:
            username = request.POST['username']
            user = User.objects.create_user(username=username, password=password1)
            context = {
                'username': user.username,
                'password': password1
            }
            return render(request, "login.html", context=context)
        context['error'] = "Password do not match!"
        return render(request, "signup.html", context=context)
    return render(request, "signup.html", context=context)

def login_view(request):            
    context = {
        'form': UserForm()
    }
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if(user is not None):
            request.session['username'] = username
            login(request, user)
            return redirect(reverse('jualdatapribadi:index'))
        else:
            return render(request, "login.html", context=context)
    return render(request, "login.html", context=context)

status/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.shortcuts import get_object_or_404, render
from .forms import StatusForm
from .models import Status
from django.db.models import Q
from django.http import HttpResponseRedirect
import random
# Create your views here.

def index(request):
    if(request.method == "POST"):
        name = request.POST['name']
        content = request.POST['content']
        Status.objects.create(name=name, content=content)
        qs = Status.objects.all()[:6]
        context = {
        'queryset' : qs,
        'form' : StatusForm()
        }
        return render(request, "story7.html", context=context)
    else:
        qs = Status.objects.all()[:6]
        context = {
        'queryset' : qs,
        'form' : StatusForm()
        }
        return render(request, "story7.html", context=context)

def confirm(request):
    if(request.method == "POST"):
        name = request.POST['name']
        content = request.POST['content']
        context = {
            'name': name,
            'content': content,
        }
        return render(request, "confirm.html", context=context)

def ran(request, id):
    if(request.method == 'POST'):
        cur = Status.objects.get(id=id)
        colors = ['Red','Green', 'Blue', 'Yellow']
        rand_idx = random.randint(0,3)
        cur.color = colors[rand_idx]
        cur.save()
        return redirect(index)

tierlist/views.py
from django.shortcuts import render
from .models import About

# Create your views here.
def index(request):
    qs = About.objects.all()
    context = {
        'queryset' : qs
    }
    return render(request, 'tierlist.html', context=context)

boogle/templates/boogle.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/story9.css' %}" />
    <title>Google for books</title>
    <link rel="shortcut icon" href="https://i.imgur.com/OPh3pdh.png" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Bhaina+2&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
</head>

<body class="dark">
    <div class="modal">
        <div class="title">Most Liked Books</div>
        <div class="bookmodal open">
        </div>
    </div>
    <div class="notification"></div>
    <div class="onoffswitch">
        <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
        <label class="onoffswitch-label" for="myonoffswitch"></label>
    </div>
    <div class="title">
        <a href="">
            <h1>Boogle</h1>
        </a>
    </div>
    <div class="search">
        <svg xmlns="http://www.w3.org/2000/svg" style="display:none">
            <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-search-8" viewBox="0 0 40 40">
              <path d="M16 32c8.835 0 16-7.165 16-16 0-8.837-7.165-16-16-16C7.162 0 0 7.163 0 16c0 8.835 7.163 16 16 16zm0-5.76c5.654 0 10.24-4.586 10.24-10.24 0-5.656-4.586-10.24-10.24-10.24-5.656 0-10.24 4.584-10.24 10.24 0 5.654 4.584 10.24 10.24 10.24zM28.156 32.8c-1.282-1.282-1.278-3.363.002-4.643 1.282-1.284 3.365-1.28 4.642-.003l6.238 6.238c1.282 1.282 1.278 3.363-.002 4.643-1.283 1.283-3.366 1.28-4.643.002l-6.238-6.238z"
              fill-rule="evenodd" />
            </symbol>
            <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-clear-4" viewBox="0 0 20 20">
              <path d="M11.664 9.877l4.485 4.485-1.542 1.54-4.485-4.485-4.485 4.485-1.54-1.54 4.485-4.485-4.485-4.485 1.54-1.54 4.485 4.484 4.485-4.485 1.54 1.542-4.484 4.485zM10 20c5.523 0 10-4.477 10-10S15.523 0 10 0 0 4.477 0 10s4.477 10 10 10z" fill-rule="evenodd"
              />
            </symbol>
          </svg>
          
          <div class="sbx-facebook">
              <input id="search" type="search" placeholder="Find your favorite books on boogle" required="required">
              <button type="submit" class="enter">
                <svg  aria-label="Search">
                  <use xlink:href="#sbx-icon-search-8"></use>
                </svg>
              </button>
            </div>
    </div>
    <div class="accordionlist">
        <div class="accordion">
            <div class='header'>
                <div class="accordionheader">
                    <p>Check Boogle Ranking</p>
                </div>
            </div>
        </div>
    </div>
    <div class="books"></div>
    <div class="suspense"></div>
    <script src="{% static 'js/story9.js' %}"></script>
</body>

</html>

jualdatapribadi/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/story10.css' %}" />
    <title>MASUKKAN PASSWORD ANDA DI SINI</title>
    <link
      rel="shortcut icon"
      href="https://i.imgur.com/OPh3pdh.png"
      type="image/x-icon"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Baloo+Bhaina+2&display=swap"
      rel="stylesheet"
    />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  </head>

  <body class="dark">
    <div class="notification"></div>
    <div class="onoffswitch">
      <input
        type="checkbox"
        name="onoffswitch"
        class="onoffswitch-checkbox"
        id="myonoffswitch"
        checked
      />
      <label class="onoffswitch-label" for="myonoffswitch"></label>
    </div>
    <div class="title">
      <a href="/totallysafe/">
        {% if user.is_authenticated %}
        <h1>Welcome back, {{ user.username }}</h1>
        <img src="{{ userprof.img_url }}" alt="no-img-set" />
        {% if userprof.birthday %}
        <h1>Ultah kamu {{ userprof.birthday }} ya,<br /></h1>
        {% else %}
        <h1>Birthday not set!<br /></h1>
        {% endif %} {% if user.first_name %}
        <h1>{{ userprof.full_name }}?</h1>
        {% else %}
        <h1>First and last name not set!</h1>
        {% endif %} {% else %}
        <h1>Hello, stranger</h1>
        {% endif %}
      </a>
    </div>
    <div class="menu">
      {% if user.is_authenticated %}
      <a href="{% url 'logout' %}">
        <div class="accordionheader">
          <p>Logout</p>
        </div>
      </a>
      {% else %}
      <a href="{% url 'jualdatapribadi:signup' %}">
        <div class="accordionheader">
          <p>Signup</p>
        </div>
      </a>
      <a href="{% url 'jualdatapribadi:login' %}">
        <div class="accordionheader">
          <p>Login</p>
        </div>
      </a>
      {% endif %}
    </div>

    <script src="{% static 'js/story10.js' %}"></script>
  </body>
</html>

jualdatapribadi/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/story10.css' %}" />
    <title>MASUKKAN PASSWORD ANDA DI SINI</title>
    <link rel="shortcut icon" href="https://i.imgur.com/OPh3pdh.png" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Bhaina+2&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
</head>

<body class="dark">
    <!-- <div class="modal">
        <div class="title">Hello there!</div>
    </div> -->
    <div class="notification"></div>
    <div class="onoffswitch">
        <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
        <label class="onoffswitch-label" for="myonoffswitch"></label>
    </div>
    <div class="title">
        <a href="/totallysafe/">
            <h1>Login</h1>
        </a>
    </div>
    <div class="accordionlist">
        <form action="{% url 'jualdatapribadi:login' %}" method="POST">
            {% csrf_token %}
            {% if form != None %}
            {{form}}
            {% else %}
            <p>Username :</p>
            <input id="id_username" type="text" name="username" placeholder="enter username" value="{{ username }}" required>
            <p>Password :</p>
            <input id="id_password" type="password" name="password" placeholder="enter password" value="{{ password }}" required>
            {% endif %}
            <div class="menu">
                    <input type="submit" class="nothing" value="Login!">
                <a href="{% url 'jualdatapribadi:signup' %}">
                    <div class="accordionheader">
                        <p>Dont have one yet?</p>
                    </div>
                </a>
            </div>
        </form>
    </div>

    <div class="books"></div>
    <div class="suspense"></div>
    <script src="{% static 'js/story10.js' %}"></script>
</body>

</html>

jualdatapribadi/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/story10.css' %}" />
    <title>MASUKKAN PASSWORD ANDA DI SINI</title>
    <link rel="shortcut icon" href="https://i.imgur.com/OPh3pdh.png" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Bhaina+2&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
</head>

<body class="dark">
    <div class="notification"></div>
    <div class="onoffswitch">
        <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
        <label class="onoffswitch-label" for="myonoffswitch"></label>
    </div>
    <div class="title">
        <a href="/totallysafe/">
            <h1>Create A New User</h1>
        </a>
    </div>
    <div class="accordionlist">
        <p>{{ error }}</p>
        <form action="/totallysafe/signup/" method="POST">
            {% csrf_token %}
            {{ form }}
            <div class="menu">
                    <input type="submit" class="nothing" value="Create Account!">
                <a href="/totallysafe/login/">
                    <div class="accordionheader">
                        <p>Already have one?</p>
                    </div>
                </a>
            </div>
        </form>
    </div>
    <script src="{% static 'js/story10.js' %}"></script>
</body>

</html>

status/templates/confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/story7.css' %}" />
    <title>Jwitter</title>
</head>
<body>
    <div class="blur open">
        <div class="modal">
            <h2>Are You Sure?</h2>
            {{name}}, you are about to post the comment {{content}}
            <form action="/" method="POST">
                {% csrf_token %}
                <input type="text" name="name" value="{{ name }}" required readonly>
                <input type="text" name="content" value="{{ content }}" required readonly>
                <input type="submit" class="confirm Blue" value="Yes, post my comment">
            </form>
            <form action="/" method="GET">
                <input type="submit" class=Red value="Shit, go back">
            </form>
        </div>
    </div>
    <div class="header">
        <h1>Salah fokus</h1>
    </div>
</body>
</html>

status/templates/story7.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/story7.css' %}" />
    <title>Jwitter</title>
</head>
<body>
    <div class="blur">
        <div class="modal">
            <h2>Add A Comment</h2>
            <form action="confirm/" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" class="comment" value="Comment">
            </form>
        </div>
    </div>
    <div class="header">
        <a href="" ><h1>Review Joni Dot Com</h1></a>
    </div>
    <div class="statuslist">
        <div class="add" id="add_form">
            <p>Add Comment +</p>
        </div>
        {% for status in queryset %}
            <div class="status {{status.color}}">
                <form action="randcolor/{{status.id}}" method="POST">
                    {% csrf_token %}
                    <input type="submit" class="change" value="CLICK TO CHANGE COLOR">
                </form>
                <p>- {{status.name}}</p>
                <p class="title">{{status.content}}</p>
            </div>
        {% endfor %}
    </div>
    <script src="{% static 'js/story7.js' %}"></script>
</body>
</html>

tierlist/templates/tierlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/story8.css' %}" />
    <title>Waifu Tier List</title>
    <link rel="shortcut icon" href="https://i.imgur.com/OPh3pdh.png" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Bhaina+2&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body class="dark">
    <div class="onoffswitch">
        <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" checked>
        <label class="onoffswitch-label" for="myonoffswitch"></label>
    </div>
    <div class="title">
        <a href="" >
            <p><s>Waifu Tier List<br></s></p>
            <h1>About Joni</h1>
        </a>
    </div>
    <div class="accordionlist" id='sortable'>
        {% for about in queryset %}
        <div class="accordion" id={{about.id}}>
            <div class='header'>
                <div class="textheader">
                    {{about.title}}
                </div>
                <div class="updown">
                    <button class='Green'><p>ʌ</p></button>
                    <button class='Red'>v</button>
                </div>
            </div>
            <div class="info">
                {{about.description}}
            </div>
        </div>
        {% endfor %}
        <div class="accordion" id=0>
            <div class='header'>
                <div class="textheader">
                    Siapa waifu saya
                </div>
                <div class="updown">
                    <button class='Green'><p>ʌ</p></button>
                    <button class='Red'>v</button>
                </div>
            </div>
            <div class="info">
                <img src="https://imgur.com/7lIcAP5.gif.gif" alt="Emilia">
            </div>
        </div>
    </div>
    <script src="{% static 'js/story8.js' %}"></script>
</body>
</html>